[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
humanofi = "4u14FtDEdr1UqSXbwhDXDLi552Skm1TPodrtjKje2pmQ"

[programs.devnet]
humanofi = "4u14FtDEdr1UqSXbwhDXDLi552Skm1TPodrtjKje2pmQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsc -p tsconfig.json --noEmit false && npx mocha --timeout 1000000 tests-compiled/tests/**/*.js"
