// ========================================
// Humanofi — robots.txt (auto-generated by Next.js)
// ========================================

import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://humanofi.xyz';
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: ['/api/', '/admin/', '/wallet', '/portfolio'],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
  };
}
