// Mock data for development — replaced by Supabase + Helius sync in production

export interface Person {
  id: string;
  name: string;
  tag: string;
  price: string;
  priceNum: number;
  change: number;
  holders: number;
  marketCap: string;
  photoUrl: string;
  sparkline: number[];
  bio: string;
  story: string;
  offer: string;
  apy: number;
  country: string;
  socials: Record<string, string>;
  activityScore: number;
  vestingYear: number;
  totalUnlocked: number;
  createdAt: string;
}

const PHOTOS = [
  "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop&crop=face",
  "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=500&fit=crop&crop=face",
  "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=500&fit=crop&crop=face",
  "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=500&fit=crop&crop=face",
  "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=500&fit=crop&crop=face",
  "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=500&fit=crop&crop=face",
  "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&h=500&fit=crop&crop=face",
  "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=500&fit=crop&crop=face",
  "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=500&fit=crop&crop=face",
  "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=500&fit=crop&crop=face",
  "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&h=500&fit=crop&crop=face",
  "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=500&fit=crop&crop=face",
];

function spark(): number[] {
  return Array.from({ length: 12 }, () => Math.floor(Math.random() * 18) + 3);
}

export const PEOPLE: Person[] = [
  {
    id: "alice-dubois",
    name: "Alice Dubois",
    tag: "Founder",
    price: "$4.21",
    priceNum: 4.21,
    change: 12.4,
    holders: 12400,
    marketCap: "$2.1M",
    photoUrl: PHOTOS[0],
    sparkline: spark(),
    bio: "Founder of three startups. Deep tech & bioengineering spec. Sharing real-time decisions, mistakes, and metrics of her latest seed round.",
    story: "Alice sold her first startup at 22. After a major failure in 2023, she's back building a deep tech infrastructure company. She believes the best way to leverage her experience is radical transparency.",
    offer: "Real-time updates on her new company, unreleased pitch decks, startup frameworks, and weekly Q&As.",
    apy: 12.5,
    country: "FR",
    socials: { x: "@alice_ds", linkedin: "alicedubois" },
    activityScore: 92,
    vestingYear: 2,
    totalUnlocked: 0,
    createdAt: "2025-04-15",
  },
  {
    id: "marco-rossi",
    name: "Marco Rossi",
    tag: "Trader",
    price: "$2.87",
    priceNum: 2.87,
    change: 5.1,
    holders: 8900,
    marketCap: "$890K",
    photoUrl: PHOTOS[2],
    sparkline: spark(),
    bio: "Quant trader. 14 years on Wall St & crypto. Real-time analysis and positions shared instantly in the inner circle.",
    story: "Tired of institutional red tape, Marco went solo in 2021. He developed a proprietary AI-driven MEV infra and trades global markets from his laptop.",
    offer: "Live notifications of his major crypto/equities entries, macro-economic essays, and risk-management strategies.",
    apy: 31.2,
    country: "CH",
    socials: { x: "@marcotrades" },
    activityScore: 88,
    vestingYear: 1,
    totalUnlocked: 0,
    createdAt: "2025-11-02",
  },
  {
    id: "sarah-chen",
    name: "Sarah Chen",
    tag: "AI Researcher",
    price: "$1.94",
    priceNum: 1.94,
    change: -2.3,
    holders: 5600,
    marketCap: "$560K",
    photoUrl: PHOTOS[1],
    sparkline: spark(),
    bio: "Machine Learning PhD. Publishing early research. Currently building an open-source model that changes the baseline.",
    story: "Sarah left a FAANG AI research team because she believes breakthrough models should not be gatekept by megacorps. She's building from her garage.",
    offer: "Access to early model weights, deep-dive research notes before publication, and insights on the future of AGI.",
    apy: 8.4,
    country: "US",
    socials: { github: "sarahc", website: "sarahchen.ai" },
    activityScore: 76,
    vestingYear: 1,
    totalUnlocked: 0,
    createdAt: "2026-01-20",
  },
  {
    id: "youssef-amrani",
    name: "Youssef Amrani",
    tag: "Artist",
    price: "$1.45",
    priceNum: 1.45,
    change: 28.7,
    holders: 3200,
    marketCap: "$320K",
    photoUrl: PHOTOS[4],
    sparkline: spark(),
    bio: "Digital artist exploring the intersection of human identity and technology. Exclusive access to the creative process.",
    story: "Youssef spent years working as a commercial graphic designer until the crypto art movement gave him creative freedom.",
    offer: "Behind the scenes of unreleased pieces, early access to mints, and thoughts on the evolution of digital art.",
    apy: 5.6,
    country: "MA",
    socials: { instagram: "@youssef.art", x: "@youssefart" },
    activityScore: 95,
    vestingYear: 1,
    totalUnlocked: 0,
    createdAt: "2026-02-10",
  },
  {
    id: "elena-varga",
    name: "Elena Varga",
    tag: "Inventor",
    price: "$0.89",
    priceNum: 0.89,
    change: 7.2,
    holders: 1800,
    marketCap: "$180K",
    photoUrl: PHOTOS[3],
    sparkline: spark(),
    bio: "Hardware engineer. Working on a revolutionary medical device. Get behind the scenes of an ongoing invention.",
    story: "Elena holds 14 patents. She is currently bootstrapping her clinical hardware startup because traditional medtech VC is too slow.",
    offer: "Hardware prototyping updates, supply chain challenges, and raw founder logs.",
    apy: 4.1,
    country: "DE",
    socials: { linkedin: "elenavarga" },
    activityScore: 71,
    vestingYear: 1,
    totalUnlocked: 0,
    createdAt: "2026-03-01",
  },
  {
    id: "james-okonkwo",
    name: "James Okonkwo",
    tag: "Thinker",
    price: "$3.12",
    priceNum: 3.12,
    change: -1.5,
    holders: 6700,
    marketCap: "$670K",
    photoUrl: PHOTOS[6],
    sparkline: spark(),
    bio: "Philosopher and essayist. His takes on governance and tech ethics influence thousands of builders.",
    story: "James advocates for decentralized human coordination architectures. His writings are read by the top executives in Silicon Valley.",
    offer: "Private drafts of essays, book club debates, and very high-level network connections.",
    apy: 18.0,
    country: "UK",
    socials: { x: "@jameso_writes" },
    activityScore: 82,
    vestingYear: 1,
    totalUnlocked: 0,
    createdAt: "2025-09-18",
  },
  {
    id: "léa-martinez",
    name: "Léa Martinez",
    tag: "Founder",
    price: "$0.67",
    priceNum: 0.67,
    change: 42.1,
    holders: 940,
    marketCap: "$94K",
    photoUrl: PHOTOS[7],
    sparkline: spark(),
    bio: "Fintech founder in LatAm. Bootstrapped. Zero VC. Transparent sharing: metrics, doubts, victories.",
    story: "Léa believes emerging markets need entirely new financial rails. She's proving it can be built without Sand Hill Road capital.",
    offer: "Weekly MRR checks, operational playbooks, and raw advice on scaling in tough economies.",
    apy: 22.4,
    country: "BR",
    socials: { x: "@leamtz" },
    activityScore: 98,
    vestingYear: 1,
    totalUnlocked: 0,
    createdAt: "2026-03-15",
  },
  {
    id: "thomas-berg",
    name: "Thomas Berg",
    tag: "Trader",
    price: "$1.23",
    priceNum: 1.23,
    change: -5.8,
    holders: 2100,
    marketCap: "$210K",
    photoUrl: PHOTOS[8],
    sparkline: spark(),
    bio: "Ex-market maker. DeFi & MEV specialist. Sharing strategies and deep protocol analytics.",
    story: "Thomas spent 5 years writing bots for a major quant fund before realizing the real alpha is writing code for himself.",
    offer: "MEV strategy breakdowns, code snippets, and early alerts to protocol vulnerabilities.",
    apy: 45.2,
    country: "AE",
    socials: { x: "@berg_quant", github: "tberg" },
    activityScore: 64,
    vestingYear: 1,
    totalUnlocked: 0,
    createdAt: "2026-01-05",
  },
  {
    id: "amira-hassan",
    name: "Amira Hassan",
    tag: "Activist",
    price: "$0.45",
    priceNum: 0.45,
    change: 15.3,
    holders: 780,
    marketCap: "$78K",
    photoUrl: PHOTOS[5],
    sparkline: spark(),
    bio: "Education activist in conflict zones. Every dollar invested supports the mission directly.",
    story: "Amira has built 12 schools under active fire. Her token economy directly funds her non-profit operations sustainably.",
    offer: "Direct impact reports, uncensored updates from the field, and logistical breakdowns.",
    apy: 2.1,
    country: "LB",
    socials: { x: "@amira_edu" },
    activityScore: 89,
    vestingYear: 1,
    totalUnlocked: 0,
    createdAt: "2026-03-28",
  },
  {
    id: "nikolai-petrov",
    name: "Nikolai Petrov",
    tag: "Researcher",
    price: "$2.56",
    priceNum: 2.56,
    change: 3.4,
    holders: 4300,
    marketCap: "$430K",
    photoUrl: PHOTOS[10],
    sparkline: spark(),
    bio: "Theoretical physicist. Publishing fusion energy research before peer review. Radical science transparency.",
    story: "Nikolai thinks the academic publishing system is broken. He's tokenizing his research so believers can fund physics directly.",
    offer: "Unpublished papers, mathematical models, and AMA sessions on plasma physics.",
    apy: 6.8,
    country: "JP",
    socials: { website: "np-physics.org" },
    activityScore: 73,
    vestingYear: 1,
    totalUnlocked: 0,
    createdAt: "2025-12-12",
  },
  {
    id: "sofia-andersson",
    name: "Sofia Andersson",
    tag: "Designer",
    price: "$0.92",
    priceNum: 0.92,
    change: 8.9,
    holders: 1500,
    marketCap: "$150K",
    photoUrl: PHOTOS[9],
    sparkline: spark(),
    bio: "Product designer at a unicorn. Sharing design frameworks, decision trees, and unreleased side projects.",
    story: "Sofia has designed interfaces used by 100M+ users daily. She believes great design is a science.",
    offer: "Figma source files, UX breakdowns of popular apps, and career advice for designers.",
    apy: 14.2,
    country: "SE",
    socials: { x: "@sofia_ux", linkedin: "sofiaandersson" },
    activityScore: 81,
    vestingYear: 1,
    totalUnlocked: 0,
    createdAt: "2026-02-20",
  },
  {
    id: "rafael-torres",
    name: "Rafael Torres",
    tag: "Musician",
    price: "$1.78",
    priceNum: 1.78,
    change: -0.7,
    holders: 2800,
    marketCap: "$280K",
    photoUrl: PHOTOS[11] || PHOTOS[0],
    sparkline: spark(),
    bio: "Composer & producer. Early access to unreleased tracks, studio BTS, and ongoing collaborations.",
    story: "Rafael left his record label to regain master rights. His token holders are his new record label.",
    offer: "Stem downloads, private listening sessions, and royalty logic breakdowns.",
    apy: 9.9,
    country: "PT",
    socials: { instagram: "@rafatorr" },
    activityScore: 86,
    vestingYear: 1,
    totalUnlocked: 0,
    createdAt: "2025-10-30",
  },
];

export const CATEGORIES = [
  "All",
  "Traders",
  "Founders",
  "Artists",
  "Thinkers",
  "Researchers",
];

export function getPersonById(id: string): Person | undefined {
  return PEOPLE.find((p) => p.id === id);
}
